### PR TITLE
Add image for gch 8.4.1

### PR DESCRIPTION
**Pull request by VictorDenisov**

### CODE REVIEW

**Comment by phadej** [comment]
Please include cabal-install 2.2 
https://www.haskell.org/cabal/download.html

**Comment by VictorDenisov** [comment]
@phadej I addressed your request. Please take another look.

**Comment by VictorDenisov** [comment]
@phadej Could you please publish the 8.4.1 image on docker hub?

**Comment by phadej** [comment]
triggered 8.4.1, 8.4.2 and 8.4.2-ubuntu

**Pull request merged**
